language: rust

cache:
  directories:
    - $HOME/.cargo/bin

rust:
  - stable
before_script:
  - rustup component add clippy
  - rustup component add rustfmt
script:
  - cargo clippy --all-targets --all-features -- -D warnings
  - cargo fmt -- --check
  - cargo build
  - cargo run --example forward
  - cargo run --example learn
